Captured
    {
      "test": 5
    }
    Test error
        Test cause
        {
          "error": "test"
        }